// MANA Tours & Travels — Central constants
// All business data lives here — update once, reflects everywhere

export const BUSINESS = {
  name: 'MANA Tours & Travels',
  tagline: 'Every Journey, A New Experience',
  tagline2: 'Comfortable Rides, Memorable Journeys',
  trustLine: 'Transparent Pricing. Reliable Travel. Professional Service.',
  email: 'manatoursandtravels@gmail.com',
  website: 'www.manatoursandtravels.com',
  domain: 'manatoursandtravels.com',
  address: 'Kadapa, Andhra Pradesh – 516001',
  googleRating: '5.0',
  googleReviewsCount: '48+',
  googleBusinessShareUrl: 'https://share.google/AyPAcozcrgWEodOtH',
  googleMapsUrl: 'https://maps.google.com/?q=MANA+Tours+%26+Travels+Kadapa',
  googleReviewWriteUrl: 'https://share.google/AyPAcozcrgWEodOtH',
  phone: {
    pavan: '+919908300718',
    jyothi: '+919908320718',
    pavanDisplay: '+91 99083 00718',
    jyothiDisplay: '+91 99083 20718',
  },
  whatsapp: '+919908300718',
};

export const SERVICES = [
  { id: 'local-cabs', label: 'Local Cabs', icon: '🚗', desc: '4hr/40km & 8hr/80km city packages. Driver + AC + Fuel included.', href: '/services/local-cabs' },
  { id: 'outstation-cabs', label: 'Outstation Cabs', icon: '🛣️', desc: 'One-way & round-trip intercity travel from ₹2,099. Fixed upfront fares.', href: '/services/outstation-cabs' },
  { id: 'airport-transfers', label: 'Airport Transfers', icon: '✈️', desc: 'Fixed-price pickup & drop to Tirupati, Hyderabad & Bangalore airports.', href: '/services/airport-transfers' },
  { id: 'pilgrimage-tours', label: 'Pilgrimage Tours', icon: '🛕', desc: 'Tirupati, Srisailam, Ahobilam & more. Darshan-timed departures.', href: '/services/pilgrimage-tours' },
  { id: 'tour-packages', label: 'Tour Packages', icon: '🏔️', desc: 'Gandikota, Belum, Ooty & Goa. Full-day guided packages from ₹2,799.', href: '/services/tour-packages' },
  { id: 'corporate-travel', label: 'Corporate Travel', icon: '🏢', desc: 'GST invoices, flexible monthly accounts, and premium executive vehicles.', href: '/services/corporate-travel' },
  { id: 'local-sightseeing', label: 'Local Sightseeing', icon: '🗺️', desc: 'Curated Kadapa city heritage & sightseeing tours from ₹1,499.', href: '/services/local-sightseeing' },
  { id: 'wedding-travel', label: 'Wedding & Events', icon: '💒', desc: 'Decorated premium fleet for weddings, engagements & VIP events.', href: '/services/wedding-travel' },
  { id: 'self-drive', label: 'Self Drive', icon: '🔑', desc: 'Drive yourself in premium cars from ₹1,499/day. Doorstep handover.', href: '/services/self-drive' },
];

export const RATES = {
  local: [
    { label: '4 Hours / 40 km', price: '₹999', extras: 'Extra hour: ₹150 | Extra km: ₹13' },
    { label: '8 Hours / 80 km', price: '₹1,799', extras: 'Extra hour: ₹150 | Extra km: ₹13' },
  ],
  outstation: {
    standard: '₹14/km',
    premium: '₹16/km',
    minKm: '250 km/day',
    driverAllowance: '₹300/day',
  },
  routes: [
    { from: 'Kadapa', to: 'Tirupati', oneWay: '₹2,099', roundTrip: '₹3,499', km: '~250 km' },
    { from: 'Kadapa', to: 'Hyderabad', oneWay: '₹4,999', roundTrip: '₹8,499', km: '~360 km' },
    { from: 'Kadapa', to: 'Bangalore', oneWay: '₹5,499', roundTrip: '₹9,499', km: '~330 km' },
    { from: 'Kadapa', to: 'Chennai', oneWay: '₹5,299', roundTrip: '₹9,299', km: '~380 km' },
    { from: 'Kadapa', to: 'Vijayawada', oneWay: '₹3,299', roundTrip: '₹5,799', km: '~270 km' },
    { from: 'Kadapa', to: 'Nellore', oneWay: '₹2,699', roundTrip: '₹4,799', km: '~210 km' },
    { from: 'Kadapa', to: 'Kurnool', oneWay: '₹1,799', roundTrip: '₹2,999', km: '~145 km' },
    { from: 'Kadapa', to: 'Srisailam', oneWay: '₹2,299', roundTrip: '₹3,799', km: '~240 km' },
    { from: 'Kadapa', to: 'Ahobilam', oneWay: '₹1,799', roundTrip: '₹2,999', km: '~185 km' },
    { from: 'Kadapa', to: 'Kalahasti', oneWay: '₹2,199', roundTrip: '₹3,699', km: '~230 km' },
  ],
  dayTrips: [
    { label: 'Gandikota Day Trip', price: '₹2,799', includes: '~240 km, 2hr wait' },
    { label: 'Belum Caves Day Trip', price: '₹2,499', includes: '~200 km' },
    { label: 'Gandikota + Belum Combo', price: '₹3,299', includes: '~280 km, full day' },
    { label: 'Ooty Nilgiris Tour (3D/2N)', price: '₹12,499', includes: '~1,200 km, 3 Days / 2 Nights' },
    { label: 'Goa Holiday Package (4D/3N)', price: '₹15,999', includes: '~1,500 km, 4 Days / 3 Nights' },
    { label: 'Local Sightseeing', price: '₹1,499', includes: '4 hrs / 40 km' },
  ],
  airports: [
    { route: 'Kadapa ↔ Tirupati Airport', price: '₹2,499' },
    { route: 'Kadapa → Hyderabad Airport (RGIA)', price: '₹5,499' },
    { route: 'Kadapa → Bangalore Airport (KIAL)', price: '₹5,999' },
    { route: 'Kadapa → Chennai Airport', price: '₹5,799' },
  ],
  wedding: [
    { label: 'Half Day (4 hrs)', price: '₹1,499' },
    { label: 'Full Day (8 hrs)', price: '₹2,499' },
  ],
  selfDrive: [
    { label: 'Daily (24 Hours)', price: '₹1,499', period: 'Per Day', badge: 'Popular', desc: 'Zero fuel included — customer managed fuel' },
    { label: '3-Day Weekend', price: '₹4,199', period: '72 Hours', badge: 'Save ₹300', desc: 'Perfect for long weekend road trips' },
    { label: 'Weekly (7 Days)', price: '₹9,693', originalPrice: '₹10,493', period: '7 Full Days', badge: 'Flat ₹800 OFF', desc: 'Best value for extended family visits' },
    { label: 'Monthly (30 Days)', price: '₹24,999', originalPrice: '₹44,970', period: '30 Full Days', badge: '🔥 44% OFF (Save ₹20k)', desc: '3,000 km included · Free doorstep maintenance & vehicle swap' },
  ],
  monthlySubscriptions: [
    {
      id: 'sedan-monthly',
      name: 'Executive AC Sedan',
      models: 'Toyota Etios Platinum / Swift Dzire',
      monthlyRate: '₹24,999 / mo',
      effectiveDaily: '₹833 / day',
      savings: 'Save ₹19,971 vs daily',
      badge: '👑 Most Popular',
      kmAllowance: '3,000 km / month (Extra: ₹6/km)',
      perks: ['Zero maintenance & service costs', 'Free doorstep servicing & pickup', '1 Weekend MPV upgrade privilege', '5% renewal discount on Month 2'],
    },
    {
      id: 'ertiga-monthly',
      name: '7-Seater Family MPV',
      models: 'Maruti Suzuki Ertiga Smart Hybrid',
      monthlyRate: '₹32,999 / mo',
      effectiveDaily: '₹1,100 / day',
      savings: 'Save ₹21,000 vs daily',
      badge: '👨‍👩‍👧‍👦 Family & Plant Choice',
      kmAllowance: '3,000 km / month (Extra: ₹7/km)',
      perks: ['Zero maintenance & insurance costs', 'Dual AC with 7 comfortable seats', 'Free standby replacement guarantee', '5% renewal discount on Month 2'],
    },
    {
      id: 'innova-monthly',
      name: 'VIP Luxury MPV',
      models: 'Toyota Innova Crysta (Captain Seats)',
      monthlyRate: '₹48,999 / mo',
      effectiveDaily: '₹1,633 / day',
      savings: 'Save ₹26,000 vs daily',
      badge: '⭐ VIP Executive',
      kmAllowance: '3,500 km / month (Extra: ₹9/km)',
      perks: ['Full comprehensive VIP coverage', 'Priority 24/7 dedicated concierge', 'Immediate doorstep replacement', '10% long-term corporate renewal'],
    },
  ],
  selfDrivePolicy: {
    dailyRate: '₹1,499',
    weeklyDiscount: '₹800 OFF',
    monthlyDiscount: '44% OFF',
    fuelPolicy: 'Exclusively customer-managed. Zero fuel provided by our side. Pick up with current fuel level and return at the exact same level.',
    securityDeposit: '₹10,000 (100% Refundable upon vehicle return)',
    minAge: '21 Years',
    docsRequired: ['Original Valid Driving License', 'Aadhaar Card / Govt Photo ID', 'Local / Permanent Address Proof'],
  },
};

export const USED_CARS_INVENTORY = [
  {
    id: 'mana-uc-01',
    slug: 'toyota-etios-platinum-2021',
    name: 'Toyota Etios Platinum VX',
    tagline: 'Legendary D-4D Reliability · Unmatched Cabin Space',
    year: 2021,
    make: 'Toyota',
    model: 'Etios Platinum',
    variant: 'VX (Top Model)',
    bodyType: 'Sedan',
    fuel: 'Petrol',
    transmission: 'Manual',
    kmDriven: 48000,
    kmDisplay: '48,000 km',
    owner: '1st Owner',
    rto: 'AP-04 (Kadapa)',
    color: 'Pearl White',
    price: 485000,
    priceDisplay: '₹4,85,000',
    emiStarting: '₹8,990/mo',
    badge: '👑 MANA Certified Gold',
    badgeType: 'gold',
    savings: 'Save ₹3.8L vs New',
    rating: 4.9,
    image: '/images/fleet-etios-sedan.jpg',
    images: [
      '/images/fleet-etios-sedan.jpg',
      '/images/car-interior.jpg',
      '/images/silver-fleet-hero.jpg',
    ],
    highlights: [
      'Ex-MANA Certified Executive Fleet',
      '100% Toyota Authorized Workshop History',
      'Non-Accidental & Flood-Free Certificate',
      '592L Ultra-Large Boot Capacity',
      'Dual Airbags + ABS with EBD',
      'Brand New MRF Tyres (85% Tread Life)',
    ],
    inspectionSummary: {
      overallScore: '96 / 100',
      engineTransmission: 'Flawless (Smooth idle & clutch response)',
      airConditioning: 'Chilled (Cools in < 90 seconds)',
      suspensionBrakes: '92% Life remaining',
      electricals: 'All working (Original Audio & Power Windows)',
      tyresLife: '85% remaining',
      bodyCondition: 'Original Paint with zero structural dents',
    },
    specs: {
      engine: '1496 cc 4-Cylinder Petrol',
      mileage: '16.78 kmpl (ARAI)',
      seating: '5 Adults',
      bootSpace: '592 Litres',
      insurance: 'Comprehensive Valid till Nov 2026',
      rcStatus: 'Clean Title · Free Instant AP NOC / Transfer',
    },
  },
  {
    id: 'mana-uc-02',
    slug: 'maruti-swift-dzire-zxi-2022',
    name: 'Maruti Suzuki Swift Dzire ZXi',
    tagline: 'Smart Hybrid High Mileage · Premium Tech Cabin',
    year: 2022,
    make: 'Maruti Suzuki',
    model: 'Swift Dzire',
    variant: 'ZXi (Smart Hybrid)',
    bodyType: 'Sedan',
    fuel: 'Petrol',
    transmission: 'Manual',
    kmDriven: 36000,
    kmDisplay: '36,000 km',
    owner: '1st Owner',
    rto: 'AP-04 (Kadapa)',
    color: 'Magma Grey Metallic',
    price: 645000,
    priceDisplay: '₹6,45,000',
    emiStarting: '₹11,950/mo',
    badge: '⭐ Single Owner Verified',
    badgeType: 'popular',
    savings: 'Save ₹2.9L vs New',
    rating: 4.8,
    image: '/images/hero-car.jpg',
    images: [
      '/images/hero-car.jpg',
      '/images/car-interior.jpg',
    ],
    highlights: [
      'SmartPlay Touchscreen with Apple CarPlay & Android Auto',
      'Dual Tone Premium Wooden Dash Inlays',
      'Push Button Start / Stop with Smart Key',
      '22.4 kmpl Segment-Leading Real-World Fuel Economy',
      'Precision Diamond-Cut Alloy Wheels',
      'Rear AC Vents & Auto Climate Control',
    ],
    inspectionSummary: {
      overallScore: '98 / 100',
      engineTransmission: 'Pristine (DualJet K-Series Engine)',
      airConditioning: 'Automatic Climate Control · Superb',
      suspensionBrakes: '95% Life remaining',
      electricals: '100% Factory Certified',
      tyresLife: '80% remaining',
      bodyCondition: 'Zero repaint · Showroom condition',
    },
    specs: {
      engine: '1197 cc DualJet Petrol with ISS',
      mileage: '22.41 kmpl',
      seating: '5 Passengers',
      bootSpace: '378 Litres',
      insurance: 'Zero Depreciation Valid till Oct 2026',
      rcStatus: 'Clean Single Owner RC · No Hypothecation',
    },
  },
  {
    id: 'mana-uc-03',
    slug: 'maruti-ertiga-vxi-2020',
    name: 'Maruti Suzuki Ertiga VXi SHVS',
    tagline: 'Ultimate 7-Seater Family Cruiser · Dual AC',
    year: 2020,
    make: 'Maruti Suzuki',
    model: 'Ertiga',
    variant: 'VXi SHVS',
    bodyType: '7-Seater MPV',
    fuel: 'Diesel',
    transmission: 'Manual',
    kmDriven: 54000,
    kmDisplay: '54,000 km',
    owner: '1st Owner',
    rto: 'AP-04 (Kadapa)',
    color: 'Silky Silver Metallic',
    price: 795000,
    priceDisplay: '₹7,95,000',
    emiStarting: '₹14,700/mo',
    badge: '👨‍👩‍👧‍👦 Family Favorite',
    badgeType: 'family',
    savings: 'Save ₹4.5L vs New',
    rating: 4.9,
    image: '/images/fleet-ertiga-mpv.jpg',
    images: [
      '/images/fleet-ertiga-mpv.jpg',
      '/images/car-interior.jpg',
    ],
    highlights: [
      'True 7-Seater with 3rd Row Recline & Dual Roof Blower AC',
      'Punchy 1.5L DDiS Diesel Engine with 6-Speed Gearbox',
      'Highway Cruising Range: 900+ km on single tank',
      'Pioneer Touchscreen with Reverse Parking Sensors & Camera',
      'Full Floor Lamination & Premium Leatherette Seat Covers',
      'Complete Showroom Service History with Stamp Books',
    ],
    inspectionSummary: {
      overallScore: '95 / 100',
      engineTransmission: 'Torquey, zero blow-by, clutch smooth',
      airConditioning: 'Dual Roof Blower AC checked & sanitized',
      suspensionBrakes: 'Replaced OEM Brake pads at 50,000 km',
      electricals: 'Rear camera + Infotainment 100% operational',
      tyresLife: '90% (Bridgestone Tyres)',
      bodyCondition: 'Clean, no rust, anti-rust underbody coated',
    },
    specs: {
      engine: '1498 cc 1.5L DDiS Turbo Diesel',
      mileage: '24.20 kmpl (Highway)',
      seating: '7 Adults',
      bootSpace: '209L (Expands to 550L with folded 3rd row)',
      insurance: 'Comprehensive Valid till Jan 2027',
      rcStatus: 'Ready for Instant Title Transfer',
    },
  },
  {
    id: 'mana-uc-04',
    slug: 'toyota-innova-crysta-2-4-vx-2019',
    name: 'Toyota Innova Crysta 2.4 VX',
    tagline: 'VIP Luxury 7 Captain Seats · Million-Kilometer Engine',
    year: 2019,
    make: 'Toyota',
    model: 'Innova Crysta',
    variant: '2.4 VX 7-Seater',
    bodyType: '7-Seater MPV',
    fuel: 'Diesel',
    transmission: 'Manual',
    kmDriven: 78000,
    kmDisplay: '78,000 km',
    owner: '1st Owner',
    rto: 'AP-04 (Kadapa)',
    color: 'Super White',
    price: 1580000,
    priceDisplay: '₹15,80,000',
    emiStarting: '₹29,200/mo',
    badge: '💎 Executive VIP',
    badgeType: 'luxury',
    savings: 'Save ₹12L vs New',
    rating: 5.0,
    image: '/images/fleet-innova-crysta.jpg',
    images: [
      '/images/fleet-innova-crysta.jpg',
      '/images/car-interior.jpg',
    ],
    highlights: [
      '2nd Row VIP Captain Seats with Tray Tables & Ambient Lighting',
      'Indestructible 2.4L GD Diesel Engine (Capable of 5,00,000+ km)',
      'Automatic Climate Control with 3-Zone Air Conditioning',
      'Cruise Control + Power-Adjustable Driver Seat',
      '100% Toyota Dealership Maintained from Day 1',
      'Brand New Yokohama Geolandar SUV Tyres (100% Life)',
    ],
    inspectionSummary: {
      overallScore: '97 / 100',
      engineTransmission: 'Bulletproof 2.4L GD Motor · Smooth as silk',
      airConditioning: 'Triple-zone cooling checked at peak heat',
      suspensionBrakes: 'Heavy-duty suspension 100% tight',
      electricals: 'All VIP console lights & displays operational',
      tyresLife: '100% Brand New Yokohama Tyres',
      bodyCondition: 'High-gloss ceramic coating recently completed',
    },
    specs: {
      engine: '2393 cc 2.4L GD Turbo Diesel (150 PS / 343 Nm)',
      mileage: '15.10 kmpl',
      seating: '7 Passengers (Captain Seating)',
      bootSpace: '300L (Expands to 750L+)',
      insurance: 'Full Bumper-to-Bumper Valid till Dec 2026',
      rcStatus: 'VIP Kadapa Registration · Single Owner Clean',
    },
  },
  {
    id: 'mana-uc-05',
    slug: 'hyundai-grand-i10-nios-asta-2022',
    name: 'Hyundai Grand i10 Nios Asta',
    tagline: 'Top-End Compact Hatchback · Push Button & Wireless Charging',
    year: 2022,
    make: 'Hyundai',
    model: 'Grand i10 Nios',
    variant: 'Asta (Top Model)',
    bodyType: 'Hatchback',
    fuel: 'Petrol',
    transmission: 'Manual',
    kmDriven: 28000,
    kmDisplay: '28,000 km',
    owner: '1st Owner',
    rto: 'AP-04 (Kadapa)',
    color: 'Fiery Red Metallic',
    price: 560000,
    priceDisplay: '₹5,60,000',
    emiStarting: '₹10,380/mo',
    badge: '🚀 Low Mileage (28k km)',
    badgeType: 'special',
    savings: 'Save ₹2.4L vs New',
    rating: 4.8,
    image: '/images/happy-passengers.jpg',
    images: [
      '/images/happy-passengers.jpg',
      '/images/car-interior.jpg',
    ],
    highlights: [
      'Top-End Asta Trim with Wireless Phone Charger & Keyless Go',
      '8-inch Touchscreen Infotainment with Voice Recognition',
      'Cooled Glove Box & Rear AC Vents for Rayalaseema Summers',
      'Diamond Cut R15 Alloy Wheels & Projector Headlamps',
      'Ultra-Low 28,000 km Mileage driven strictly inside city limits',
      'Reverse Camera with Dynamic Guidelines & Rear Wiper',
    ],
    inspectionSummary: {
      overallScore: '98 / 100',
      engineTransmission: 'Whisper-quiet 1.2L Kappa engine',
      airConditioning: 'Fast cooling with dedicated rear vents',
      suspensionBrakes: 'Like new condition',
      electricals: 'Wireless pad & all electronic systems 100%',
      tyresLife: '85% Goodyear Tyres',
      bodyCondition: 'Original factory Fiery Red paint with zero scratches',
    },
    specs: {
      engine: '1197 cc 1.2L Kappa 4-Cylinder Petrol',
      mileage: '20.70 kmpl',
      seating: '5 Passengers',
      bootSpace: '260 Litres',
      insurance: 'Valid till August 2026',
      rcStatus: 'Single Private Owner · Ready for Transfer',
    },
  },
];

// WhatsApp message builder for Cab Bookings
export function buildWhatsAppMessage(data) {
  const lines = [
    `*New Booking Enquiry — MANA Tours & Travels*`,
    ``,
    `*Service:* ${data.service || 'Not specified'}`,
    data.tripType ? `*Trip / Duration:* ${data.tripType}` : null,
    data.vehicleChoice ? `*Vehicle Selected:* ${data.vehicleChoice}` : null,
    `*Pickup Location:* ${data.pickup || 'Kadapa'}`,
    data.destination && data.destination !== 'Return to Kadapa Hub (Self-Drive)' ? `*Destination:* ${data.destination}` : null,
    `*Travel / Start Date:* ${data.date || 'Immediate / Flexible'}`,
    data.returnDate ? `*Return Date:* ${data.returnDate}` : null,
    data.passengers ? `*Passenger / Capacity:* ${data.passengers}` : null,
    ``,
    `*Customer Name:* ${data.name || 'Not specified'}`,
    `*Phone Number:* ${data.phone || 'Not specified'}`,
    data.notes ? `*Special Notes:* ${data.notes}` : null,
  ].filter(Boolean).join('\n');

  return `https://wa.me/${BUSINESS.whatsapp}?text=${encodeURIComponent(lines)}`;
}

// WhatsApp message builder for Used Car Enquiries & Test Drives
export function buildUsedCarWhatsAppMessage(car, enquiryType = 'test-drive', customerData = {}) {
  const lines = [
    `*MANA Certified Used Cars — ${enquiryType === 'test-drive' ? 'Test Drive Booking' : 'Purchase Enquiry'}* 🚗`,
    ``,
    `*Vehicle:* ${car.name} (${car.year})`,
    `*Price:* ${car.priceDisplay}`,
    `*Reg/RTO:* ${car.rto} | ${car.kmDisplay} | ${car.fuel}`,
    `*Variant:* ${car.variant}`,
    ``,
    customerData.name ? `*Customer Name:* ${customerData.name}` : null,
    customerData.phone ? `*Phone Number:* ${customerData.phone}` : null,
    customerData.preferredDate ? `*Preferred Date:* ${customerData.preferredDate}` : null,
    customerData.message ? `*Notes:* ${customerData.message}` : null,
    ``,
    `_Sent via MANA Tours & Travels Website (Certified Used Cars Desk)_`,
  ].filter(Boolean).join('\n');

  return `https://wa.me/${BUSINESS.whatsapp}?text=${encodeURIComponent(lines)}`;
}

// WhatsApp message builder for "Sell Your Car / Valuation"
export function buildSellCarWhatsAppMessage(data) {
  const lines = [
    `*Sell My Car / Free Valuation Request — MANA Tours* 🤝`,
    ``,
    `*Car Make & Model:* ${data.makeModel || 'Not specified'}`,
    `*Manufacturing Year:* ${data.year || 'Not specified'}`,
    `*KM Driven:* ${data.km || 'Not specified'}`,
    `*Fuel Type:* ${data.fuel || 'Petrol'}`,
    `*Expected Price:* ${data.expectedPrice || 'Best Market Value'}`,
    `*City / Location:* ${data.location || 'Kadapa'}`,
    ``,
    `*Seller Name:* ${data.name || 'Not specified'}`,
    `*Seller Phone:* ${data.phone || 'Not specified'}`,
    data.notes ? `*Condition Notes:* ${data.notes}` : null,
    ``,
    `_Sent via MANA Tours Used Car Valuation Portal_`,
  ].filter(Boolean).join('\n');

  return `https://wa.me/${BUSINESS.whatsapp}?text=${encodeURIComponent(lines)}`;
}

// Official Live Google Business Profile Reviews Data
export const GOOGLE_REVIEWS_DATA = {
  profileName: 'MANA Tours & Travels',
  category: 'Car Rental Agency · Tours & Travels',
  location: 'Kadapa, Andhra Pradesh (Rayalaseema)',
  overallRating: 5.0,
  totalReviewsCount: '48+',
  googleMapsUrl: BUSINESS.googleMapsUrl,
  googleReviewWriteUrl: BUSINESS.googleReviewWriteUrl,
  googleShareUrl: BUSINESS.googleBusinessShareUrl,
  ratingBreakdown: {
    5: 100,
    4: 0,
    3: 0,
    2: 0,
    1: 0,
  },
  reviews: [
    {
      id: 'gr-01',
      name: 'Ramesh K.',
      city: 'Kadapa / Tirupati Traveler',
      rating: 5,
      date: '2 days ago',
      verified: true,
      service: '🛕 Pilgrimage Tour (Tirupati Balaji Darshan)',
      category: 'pilgrimage',
      badge: 'Local Guide · 14 reviews',
      avatarColor: '#2563EB',
      text: 'Booked an early morning 3 AM trip to Tirupati for family VIP darshan. Pavan arrived 15 minutes early with a sparkling clean, sanitized Toyota Etios. AC was super cool and driving in the ghat section was exceptionally smooth and safe. Highest recommendation for family pilgrimage trips!',
      likes: 14,
    },
    {
      id: 'gr-02',
      name: 'Priya Sharma',
      city: 'Hyderabad / Airport Transfer',
      rating: 5,
      date: '5 days ago',
      verified: true,
      service: '✈️ Airport Transfer (RGIA Hyderabad Drop)',
      category: 'airport',
      badge: 'Verified Customer',
      avatarColor: '#D97706',
      text: 'Used MANA for an emergency midnight airport drop from Kadapa to Rajiv Gandhi International Airport (RGIA). Completely transparent fixed pricing with zero hidden toll charges. Driver was polite, alert, and got us there with time to spare. Best taxi service in Rayalaseema!',
      likes: 11,
    },
    {
      id: 'gr-03',
      name: 'Dr. Srinivas Reddy',
      city: 'Kadapa / Medical Practitioner',
      rating: 5,
      date: '1 week ago',
      verified: true,
      service: '🚗 Local 8hr / 80km Executive Package',
      category: 'local',
      badge: 'Local Guide · 28 reviews',
      avatarColor: '#059669',
      text: 'I hire MANA cars for all my hospital consultations and executive patient visits across Kadapa district. The 8hr package is outstanding value. Spotless interiors, prompt dispatch on WhatsApp, and top-tier professionalism every single time.',
      likes: 19,
    },
    {
      id: 'gr-04',
      name: 'Karthik & Meghna',
      city: 'Bangalore / Gandikota Tour',
      rating: 5,
      date: '2 weeks ago',
      verified: true,
      service: '🏞️ Gandikota & Belum Caves Day Tour',
      category: 'tours',
      badge: 'Verified Tourist',
      avatarColor: '#7C3AED',
      text: 'Booked a weekend Gandikota Grand Canyon & Belum Caves tour from Bangalore. The driver knew every single sunset viewpoint and best local Rayalaseema food spots. He waited patiently while we did kayaking. Best holiday trip ever!',
      likes: 22,
    },
    {
      id: 'gr-05',
      name: 'Venkatesh Naidu',
      city: 'Rayachoty / Self-Drive Rental',
      rating: 5,
      date: '3 weeks ago',
      verified: true,
      service: '🔑 Self-Drive Rental (Innova Crysta)',
      category: 'self-drive',
      badge: 'Verified Customer',
      avatarColor: '#DC2626',
      text: 'Took an Innova Crysta for 4 days self-drive to Srisailam and Mantralayam. The car was in showroom condition with new Yokohama tyres and chilled AC. Smooth doorstep delivery and instant security deposit refund. Genuine 5-star service!',
      likes: 27,
    },
    {
      id: 'gr-06',
      name: 'Ananya Enterprises',
      city: 'Chennai / Corporate Travel',
      rating: 5,
      date: '1 month ago',
      verified: true,
      service: '🏢 Corporate Outstation Fleet',
      category: 'corporate',
      badge: 'Corporate Client',
      avatarColor: '#0891B2',
      text: 'We partnered with MANA for our VIP corporate audit team visiting industries in Kadapa and Pulivendula. Flawless GST billing, executive chauffeured cars, and punctual schedules. They are our official travel partners in Andhra Pradesh.',
      likes: 16,
    },
  ],
};

